import { Metadata } from "next";
import "./global.css";
import ErrorWrapper from "./error-wrapper";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - codevolution",
    template: "%s | codevolution",
    // absolute: "",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col h-screen border-1">
        <header className="bg-blue-400 p-4 flex-none">
          <p>Header</p>
        </header>
        <div className="bg-white grow">
          <ErrorWrapper>{children}</ErrorWrapper>
        </div>
        <footer className="bg-blue-200 p-4 flex-none">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
