services:
  drupal:
    image: drupal:9
    ports:
      - 8080:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    restart: always

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: example
    restart: always
